Community ad/clifford/feat/endpoint get
UNSRAT-IT-Community/back-end-web-unity pull request #6
Opened 2024-07-09 01:13 UTC by CliffCodeApe

# Feat: Buat endpoint Get dan Get berdasarkan Uuid Community Ads

## Endpoint Get
1. Index
![image](https://github.com/UNSRAT-IT-Community/back-end-web-unity/assets/161431169/cc703acd-6495-4be4-a5dd-c8c28ca95424)

2. Show
![image](https://github.com/UNSRAT-IT-Community/back-end-web-unity/assets/161431169/4f86982f-63c0-48ad-85dc-04212a733934)

3. Mengubah Nama middleware sesuai dengan role dalam Role Seeder
![image](https://github.com/UNSRAT-IT-Community/back-end-web-unity/assets/161431169/f29c6507-b287-431f-bd65-4444914c4c1f)

2024-07-09 05:11 UTC, zharkaa requested changes
blh feedbacknya dari bapak @CliffCodeApe @albertnanda19

2024-07-09 05:11 UTC, zharkaa commented on routes/api.php
> +
hmmm, ini kan community ad, klo dpe route taru disini cuma user yang punya role coordinator yang bisa lihat dpe `ad`. 

klo dari qt sih, dpe endpoint `GET` for community ad ditempatkan, antara user dengan role `member` ato user public. klo for user public drng bisa lihat itu `ad` yang diposting, kan maksud dari `ad` ini mo iklankan trng pe produk.

mungkin dari @albertnanda19 ada masukkan soal ini ?

2024-07-09 14:59 UTC, CliffCodeApe commented on routes/api.php
> +
Kita ada ta salah taruh kak depe endpoint Get.

2024-07-10 03:29 UTC, albertnanda19 commented on routes/api.php
> +
Kalau kt setuju, untuk dpe endpoint `GET` itu boleh di akses oleh public 
Dan kalau boleh dpe nama endpoint ubah jadi "/community-ads"

Dan juga kt mau comment untuk validasi role itu jangan di middleware, tapi taruh di controller. Di middleware cuman ada middleware for validasi dpe token

2024-07-10 03:33 UTC, albertnanda19 commented on routes/api.php
> +
Dan jangan lupa resolve dpe conflict (tolong di perhatikan baik-baik)

2024-07-10 13:03 UTC, zharkaa approved these changes
LGTM!

2024-07-10 13:16 UTC, zharkaa approved these changes
LGTM!

2024-07-10 13:16 UTC, merged